# Project Information
site_name: NewDocs
site_description: Distributed Asynchronous Object Storage
site_author: Docs Project
site_url: https://cdurf1.github.io/
site_dir: ../site

# Repository
repo_name: cdurf1/cdurf1.github.io
repo_url: https://github.com/cdurf1/cdurf1.github.io/site
edit_url: ""

# Theme
theme:
      name: 'material'
      font:
            text: 'Ubuntu'
            code: 'Ubuntu Mono'
      language: en
      palette:
            primary: 'blue grey'
            accent: 'blue'
      feature:
            tabs: true
      logo: daos_logo.png

docs_dir: doc

markdown_extensions:
    - admonition
    - footnotes
    - toc:
            permalink: true

# Page tree
nav:
    - Home: 'index.md'
    - Architecture Overview:
          - 'Terminology': 'overview/terminology.md'
    - Administration Guide:
          - 'Hardware Requirements': 'admin/hardware.md'
    - User Guide:
          - 'Container Management': 'user/container.md'
    - Developer Zone:
          - 'DAOS API Documentation': 'html/index.html'
extra_css:
    - css\version-select.css
extra_javascript:
    - js\version-select.js
